# library(dplyr)
# 
# source("/home/bastian/Dataemprende/rutas.r") #recomendacion()
# 
# recomendacion(nombre = "empresa que vende online",
#               v_nivel = 3, v_deseo = 1, v_conoc = 3, v_recur = 1, v_compe = 3,
#               v_rubro = "Comercio al por mayor y al por menor, reparación de vehículos automotores y motocicletas")


cursos_tabla <- tribble(~curso,                                  ~titulo,                                              ~nivel,
                        "introducción",                          "Introducción a la transformación digital",           2,
                        "evangelización",                        "¿Por qué digitalizar su negocio o empresa?",         1,
                        "aplicación",                            "Curso práctico: primer acercamiento a las tecnologías digitales aplicadas a su negocio o empresa", 1,
                        "postulación a proyectos",               "Postulación a fondos concursables o beneficios para su negocio o empresa",                 1,
                        "herramientas básicas",                  "Herramientas digitales 1:",                          3,
                        "herramientas intermedias",              "Herramientas digitales 2:",                          4,
                        "herramientas avanzadas",                "Herramientas digitales 3:",                          4,
                        "innovación",                            "Innovación mediante la aplicación de tecnologías digitales",                               3,
                        "temático 1: marketing digital",         "Aplicando herramientas digitales a su negocio: marketing digital y redes sociales",        3,
                        "temático 2: ventas online",             "Aplicando herramientas digitales a su negocio: ventas online",                             3,
                        "temático 3: análisis de datos",         "Aplicando herramientas digitales a su negocio: análisis de datos",                         3,
                        "temático 4: herramientas financieras",  "Aplicando herramientas digitales a su negocio: digitalizando sus finanzas y contabilidad", 3,
                        "temático 5: logística",                 "Aplicando herramientas digitales a su negocio: digitalizando su logística",                3
                        ) |> 
  mutate(id_curso = janitor::make_clean_names(curso, case = "snake"))

#descripción ----
#cursos_tabla |> select(id_curso) |> datapasta::dpasta()
cursos_descripcion <- tibble::tribble(
                              ~id_curso, ~descripcion,
                         "introduccion", "En este curso introduccion aprenderás consectetur adipiscing elit. Aenean vitae tincidunt quam. Vestibulum efficitur libero eu purus congue mattis. Nullam ut viverra turpis. Donec id commodo ligula, quis aliquam turpis. Mauris feugiat at tortor non blandit. In maximus sollicitudin risus, non faucibus massa lobortis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc rhoncus ultrices quam. Aenean dapibus blandit magna id aliquam. \nDuis mauris justo, molestie a leo vitae, malesuada laoreet nisi. Integer mattis convallis commodo. Curabitur dictum purus vel orci tempor tempus.",
                       "evangelizacion", "En este curso evangelizacion aprenderás consectetur adipiscing elit. Aenean vitae tincidunt quam. Vestibulum efficitur libero eu purus congue mattis. Nullam ut viverra turpis. Donec id commodo ligula, quis aliquam turpis. Mauris feugiat at tortor non blandit. In maximus sollicitudin risus, non faucibus massa lobortis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc rhoncus ultrices quam. Aenean dapibus blandit magna id aliquam. \nDuis mauris justo, molestie a leo vitae, malesuada laoreet nisi. Integer mattis convallis commodo. Curabitur dictum purus vel orci tempor tempus.",
                           "aplicacion", "En este curso aplicacion aprenderás consectetur adipiscing elit. Aenean vitae tincidunt quam. Vestibulum efficitur libero eu purus congue mattis. Nullam ut viverra turpis. Donec id commodo ligula, quis aliquam turpis. Mauris feugiat at tortor non blandit. In maximus sollicitudin risus, non faucibus massa lobortis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc rhoncus ultrices quam. Aenean dapibus blandit magna id aliquam. \nDuis mauris justo, molestie a leo vitae, malesuada laoreet nisi. Integer mattis convallis commodo. Curabitur dictum purus vel orci tempor tempus.",
              "postulacion_a_proyectos", "En este curso postulacion_a_proyectos aprenderás consectetur adipiscing elit. Aenean vitae tincidunt quam. Vestibulum efficitur libero eu purus congue mattis. Nullam ut viverra turpis. Donec id commodo ligula, quis aliquam turpis. Mauris feugiat at tortor non blandit. In maximus sollicitudin risus, non faucibus massa lobortis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc rhoncus ultrices quam. Aenean dapibus blandit magna id aliquam. \nDuis mauris justo, molestie a leo vitae, malesuada laoreet nisi. Integer mattis convallis commodo. Curabitur dictum purus vel orci tempor tempus.",
                 "herramientas_basicas", "En este curso herramientas_basicas aprenderás consectetur adipiscing elit. Aenean vitae tincidunt quam. Vestibulum efficitur libero eu purus congue mattis. Nullam ut viverra turpis. Donec id commodo ligula, quis aliquam turpis. Mauris feugiat at tortor non blandit. In maximus sollicitudin risus, non faucibus massa lobortis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc rhoncus ultrices quam. Aenean dapibus blandit magna id aliquam. \nDuis mauris justo, molestie a leo vitae, malesuada laoreet nisi. Integer mattis convallis commodo. Curabitur dictum purus vel orci tempor tempus.",
             "herramientas_intermedias", "En este curso herramientas_intermedias aprenderás consectetur adipiscing elit. Aenean vitae tincidunt quam. Vestibulum efficitur libero eu purus congue mattis. Nullam ut viverra turpis. Donec id commodo ligula, quis aliquam turpis. Mauris feugiat at tortor non blandit. In maximus sollicitudin risus, non faucibus massa lobortis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc rhoncus ultrices quam. Aenean dapibus blandit magna id aliquam. \nDuis mauris justo, molestie a leo vitae, malesuada laoreet nisi. Integer mattis convallis commodo. Curabitur dictum purus vel orci tempor tempus.",
               "herramientas_avanzadas", "En este curso herramientas_avanzadas aprenderás consectetur adipiscing elit. Aenean vitae tincidunt quam. Vestibulum efficitur libero eu purus congue mattis. Nullam ut viverra turpis. Donec id commodo ligula, quis aliquam turpis. Mauris feugiat at tortor non blandit. In maximus sollicitudin risus, non faucibus massa lobortis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc rhoncus ultrices quam. Aenean dapibus blandit magna id aliquam. \nDuis mauris justo, molestie a leo vitae, malesuada laoreet nisi. Integer mattis convallis commodo. Curabitur dictum purus vel orci tempor tempus.",
                           "innovacion", "En este curso innovacion aprenderás consectetur adipiscing elit. Aenean vitae tincidunt quam. Vestibulum efficitur libero eu purus congue mattis. Nullam ut viverra turpis. Donec id commodo ligula, quis aliquam turpis. Mauris feugiat at tortor non blandit. In maximus sollicitudin risus, non faucibus massa lobortis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc rhoncus ultrices quam. Aenean dapibus blandit magna id aliquam. \nDuis mauris justo, molestie a leo vitae, malesuada laoreet nisi. Integer mattis convallis commodo. Curabitur dictum purus vel orci tempor tempus.",
         "tematico_1_marketing_digital", "En este curso tematico_1_marketing_digital aprenderás consectetur adipiscing elit. Aenean vitae tincidunt quam. Vestibulum efficitur libero eu purus congue mattis. Nullam ut viverra turpis. Donec id commodo ligula, quis aliquam turpis. Mauris feugiat at tortor non blandit. In maximus sollicitudin risus, non faucibus massa lobortis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc rhoncus ultrices quam. Aenean dapibus blandit magna id aliquam. \nDuis mauris justo, molestie a leo vitae, malesuada laoreet nisi. Integer mattis convallis commodo. Curabitur dictum purus vel orci tempor tempus.",
             "tematico_2_ventas_online", "En este curso tematico_2_ventas_online aprenderás consectetur adipiscing elit. Aenean vitae tincidunt quam. Vestibulum efficitur libero eu purus congue mattis. Nullam ut viverra turpis. Donec id commodo ligula, quis aliquam turpis. Mauris feugiat at tortor non blandit. In maximus sollicitudin risus, non faucibus massa lobortis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc rhoncus ultrices quam. Aenean dapibus blandit magna id aliquam. \nDuis mauris justo, molestie a leo vitae, malesuada laoreet nisi. Integer mattis convallis commodo. Curabitur dictum purus vel orci tempor tempus.",
         "tematico_3_analisis_de_datos", "En este curso tematico_3_analisis_de_datos aprenderás consectetur adipiscing elit. Aenean vitae tincidunt quam. Vestibulum efficitur libero eu purus congue mattis. Nullam ut viverra turpis. Donec id commodo ligula, quis aliquam turpis. Mauris feugiat at tortor non blandit. In maximus sollicitudin risus, non faucibus massa lobortis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc rhoncus ultrices quam. Aenean dapibus blandit magna id aliquam. \nDuis mauris justo, molestie a leo vitae, malesuada laoreet nisi. Integer mattis convallis commodo. Curabitur dictum purus vel orci tempor tempus.",
  "tematico_4_herramientas_financieras", "En este curso tematico_4_herramientas_financieras aprenderás consectetur adipiscing elit. Aenean vitae tincidunt quam. Vestibulum efficitur libero eu purus congue mattis. Nullam ut viverra turpis. Donec id commodo ligula, quis aliquam turpis. Mauris feugiat at tortor non blandit. In maximus sollicitudin risus, non faucibus massa lobortis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc rhoncus ultrices quam. Aenean dapibus blandit magna id aliquam. \nDuis mauris justo, molestie a leo vitae, malesuada laoreet nisi. Integer mattis convallis commodo. Curabitur dictum purus vel orci tempor tempus.",
                 "tematico_5_logistica", "En este curso tematico_4_herramientas_financieras aprenderás consectetur adipiscing elit. Aenean vitae tincidunt quam. Vestibulum efficitur libero eu purus congue mattis. Nullam ut viverra turpis. Donec id commodo ligula, quis aliquam turpis. Mauris feugiat at tortor non blandit. In maximus sollicitudin risus, non faucibus massa lobortis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc rhoncus ultrices quam. Aenean dapibus blandit magna id aliquam. \nDuis mauris justo, molestie a leo vitae, malesuada laoreet nisi. Integer mattis convallis commodo. Curabitur dictum purus vel orci tempor tempus."
  )

#unir ----
cursos_tabla <- cursos_tabla |> bind_cols(cursos_descripcion |> select(descripcion))
